<a href="https://colab.research.google.com/github/Arbaz-Iqbal/AI-With-SVTTI/blob/main/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import pandas as pd
import numpy as np

In [61]:


df=pd.DataFrame({
                 'Name': ['Alice', 'Charlie', 'Bob','Alice'],
                 'Age' : [25, np.nan , 35,25],
                 'Salary' : [50000, 60000, np.nan,50000],
})

In [62]:
df

      Name   Age   Salary
0    Alice  25.0  50000.0
1  Charlie   NaN  60000.0
2      Bob  35.0      NaN
3    Alice  25.0  50000.0

#Duplicate Data Remove hojay ga

In [63]:
df=df.drop_duplicates()

In [64]:
df

      Name   Age   Salary
0    Alice  25.0  50000.0
1  Charlie   NaN  60000.0
2      Bob  35.0      NaN

In [65]:
#Missing Values ko remove krny k liye
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Salary'].fillna(df['Salary'].mean(),inplace=True)

/tmp/ipykernel_2313/2620130282.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)
/tmp/ipykernel_2313/2620130282.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'].fillna(df['Age'].mean(),inplace=True)
/tmp/ipykernel_2313/2620130282.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(),inplace=True)
/tmp/ipykernel_2313/2620130282.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salary'].fillna(df['Salary'].mean(),inplace=True)

In [66]:
df

      Name   Age   Salary
0    Alice  25.0  50000.0
1  Charlie  30.0  60000.0
2      Bob  35.0  55000.0